### ISSUE TITLE
[FEATURE] Input data source supports Kafka

### ISSUE THREAD

**Issue by D0n9** [kitabisa/teler#121]
For companies with a certain scale, Nginx is deployed in clusters, and the access.log file is distributed in each node machine, and the production environment server is not allowed to run programs that occupy unstable resources

Therefore, I hope to support Kafka as an input data source

// Thanks for open source this project, this is great work :)

**Comment by dwisiswant0** [comment]
Hi, @D0n9. Can you please elaborate more about how to (usage, command, .etc) to stream access log from Kafka?

**Comment by budiariyanto** [comment]
@dwisiswant0 I think what @D0n9 trying to say is that teler can be started as kafka consumer and listen to given topic. So when message arrive, it takes as an input for teler.

**Comment by dwisiswant0** [comment]
I believe you can stream Kafka console consumer output buffer by using some `--property` flags like turning `print.key` on & combining `key.separator` then piped it to teler as standard input will make writing log format easier, @D0n9.
If the format is JSON, you can also use jq<sup>[1]</sup> but it's a very sloppy way of doing it. See how to log format<sup>[2]</sup>.

Because the focus of engine is only to analyze an access log with as minimal configuration as possible. Closing it now.

[1] https://stedolan.github.io/jq/
[2] https://www.notion.so/kitabisa/Log-Format-43a9e43b43bf44f9aa7d2d251338698d
